services:
  minio1:
    image: minio/minio:latest
    hostname: minio1
    # Gọi tới 3 node, mỗi node có 2 thư mục data1 và data2
    command: server http://minio{1...3}/data{1...2} --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    ports:
      - "9000:9000" # Port cho S3 API
      - "9001:9001" # Port cho Web Web UI (Console)
    volumes:
      - minio1-data1:/data1
      - minio1-data2:/data2

  minio2:
    image: minio/minio:latest
    hostname: minio2
    command: server http://minio{1...3}/data{1...2} --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - minio2-data1:/data1
      - minio2-data2:/data2

  minio3:
    image: minio/minio:latest
    hostname: minio3
    command: server http://minio{1...3}/data{1...2} --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - minio3-data1:/data1
      - minio3-data2:/data2

# Khai báo các volume ảo để lưu trữ dữ liệu bền vững trên Docker
volumes:
  minio1-data1:
  minio1-data2:
  minio2-data1:
  minio2-data2:
  minio3-data1:
  minio3-data2: